/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
  0%|          | 0/14666 [00:00<?, ?it/s]  0%|          | 22/14666 [00:00<01:58, 123.90it/s]/home/atalia/fgivenx_plots/plots_fgivenx.py:80: RuntimeWarning: overflow encountered in double_scalars
  dy[5] = y[0]**2.*x**2.
/home/atalia/fgivenx_plots/plots_fgivenx.py:83: RuntimeWarning: overflow encountered in double_scalars
  dy[9] = y[6]**2.*x**2.
/home/atalia/fgivenx_plots/plots_fgivenx.py:86: RuntimeWarning: overflow encountered in double_scalars
  dy[13] = y[10]**2.*x**2.
/home/atalia/fgivenx_plots/plots_fgivenx.py:93: RuntimeWarning: overflow encountered in double_scalars
  dy[1] = 2.*(y[2]-y[4])*y[0] - 2.*y[1]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:94: RuntimeWarning: overflow encountered in double_scalars
  dy[3] = y[0]**2. + 3.*x*2.*y[6]**2. + 5.*x**4.*y[10]**2. - 2.*y[3]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:95: RuntimeWarning: overflow encountered in double_scalars
  dy[7] = 2.*(y[2] -y[8])*y[6] -4.*y[7]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:96: RuntimeWarning: overflow encountered in double_scalars
  dy[11] = 2.*(y[2]-y[12])*y[10] - 6.*y[11]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:93: RuntimeWarning: invalid value encountered in double_scalars
  dy[1] = 2.*(y[2]-y[4])*y[0] - 2.*y[1]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:94: RuntimeWarning: invalid value encountered in double_scalars
  dy[3] = y[0]**2. + 3.*x*2.*y[6]**2. + 5.*x**4.*y[10]**2. - 2.*y[3]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:95: RuntimeWarning: invalid value encountered in double_scalars
  dy[7] = 2.*(y[2] -y[8])*y[6] -4.*y[7]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:96: RuntimeWarning: invalid value encountered in double_scalars
  dy[11] = 2.*(y[2]-y[12])*y[10] - 6.*y[11]/x
  0%|          | 22/14666 [00:19<01:58, 123.90it/s]/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
  0%|          | 44/14666 [01:04<7:02:00,  1.73s/it]/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:80: RuntimeWarning: overflow encountered in double_scalars
  dy[5] = y[0]**2.*x**2.
/home/atalia/fgivenx_plots/plots_fgivenx.py:83: RuntimeWarning: overflow encountered in double_scalars
  dy[9] = y[6]**2.*x**2.
/home/atalia/fgivenx_plots/plots_fgivenx.py:86: RuntimeWarning: overflow encountered in double_scalars
  dy[13] = y[10]**2.*x**2.
/home/atalia/fgivenx_plots/plots_fgivenx.py:93: RuntimeWarning: overflow encountered in double_scalars
  dy[1] = 2.*(y[2]-y[4])*y[0] - 2.*y[1]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:94: RuntimeWarning: overflow encountered in double_scalars
  dy[3] = y[0]**2. + 3.*x*2.*y[6]**2. + 5.*x**4.*y[10]**2. - 2.*y[3]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:95: RuntimeWarning: overflow encountered in double_scalars
  dy[7] = 2.*(y[2] -y[8])*y[6] -4.*y[7]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:96: RuntimeWarning: overflow encountered in double_scalars
  dy[11] = 2.*(y[2]-y[12])*y[10] - 6.*y[11]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:93: RuntimeWarning: invalid value encountered in double_scalars
  dy[1] = 2.*(y[2]-y[4])*y[0] - 2.*y[1]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:94: RuntimeWarning: invalid value encountered in double_scalars
  dy[3] = y[0]**2. + 3.*x*2.*y[6]**2. + 5.*x**4.*y[10]**2. - 2.*y[3]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:95: RuntimeWarning: invalid value encountered in double_scalars
  dy[7] = 2.*(y[2] -y[8])*y[6] -4.*y[7]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:96: RuntimeWarning: invalid value encountered in double_scalars
  dy[11] = 2.*(y[2]-y[12])*y[10] - 6.*y[11]/x
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
  0%|          | 66/14666 [02:11<9:25:38,  2.32s/it]/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
  1%|          | 88/14666 [03:53<13:06:36,  3.24s/it]/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
  1%|          | 110/14666 [05:41<15:33:16,  3.85s/it]/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
  1%|          | 132/14666 [07:14<16:01:15,  3.97s/it]/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/home/atalia/fgivenx_plots/plots_fgivenx.py:114: RuntimeWarning: invalid value encountered in true_divide
  return (units*M)/r
/usr/local/lib/python3.9/site-packages/joblib/externals/loky/backend/resource_tracker.py:318: UserWarning: resource_tracker: There appear to be 28 leaked semlock objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/usr/local/lib/python3.9/site-packages/joblib/externals/loky/backend/resource_tracker.py:318: UserWarning: resource_tracker: There appear to be 2 leaked folder objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
